---
title: "Meteo data"
title-block: false

---
```{r}
#| echo: FALSE
#| output: FALSE
rds_folder <- "C:/Users/Kaltern/OneDrive - Scientific Network South Tyrol/Plantaditsch_repository - General/Data_dashboard/RDS_objects"

diagnostics_tbl<-readRDS(paste(rds_folder,"diagnostics_tbl.RDS",sep="/"))
EBC_rawplotly<-readRDS(paste(rds_folder,"EBC_rawplotly.RDS",sep="/"))
Tair_rawplotly<-readRDS(paste(rds_folder,"Tair_rawplotly.RDS",sep="/"))
rH_rawplotly<-readRDS(paste(rds_folder,"rH_rawplotly.RDS",sep="/"))
VPD_rawplotly<-readRDS(paste(rds_folder,"VPD_rawplotly.RDS",sep="/"))
PAR_rawplotly<-readRDS(paste(rds_folder,"PAR_rawplotly.RDS",sep="/"))
WB_rawplotly<-readRDS(paste(rds_folder,"WB_rawplotly.RDS",sep="/"))
TC_rawplotly<-readRDS(paste(rds_folder,"TC_rawplotly.RDS",sep="/"))
SWC_rawplotly<-readRDS(paste(rds_folder,"SWC_rawplotly.RDS",sep="/"))
SWP_rawplotly<-readRDS(paste(rds_folder,"SWP_rawplotly.RDS",sep="/"))
```

## Row {height="30%"}

```{r}
#| echo: FALSE
#| output: TRUE
#| title: Datalogger files imported
knitr::kable(
  diagnostics_tbl,
  format="simple",
  digits = 3
  #,caption = "Diagnostics summary for imported logger data tables"
)
```

## Row {height="50%"}

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Temperature
Tair_rawplotly
```

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Relative Humidity
rH_rawplotly

```

## Row {height="50%"}

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Vapour Pressure Deficit
VPD_rawplotly
```

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Rainfall
WB_rawplotly
```

## Row {height="50%"}

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Vol. Soil Water Content
SWC_rawplotly
```

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Soil Water Potential
SWP_rawplotly
```

## Row {height="50%"}

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Energy Balance Components
EBC_rawplotly
```

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: PAR
PAR_rawplotly
```

## Row {height="50%"}

```{r}
#| echo: false
#| output: true
#| message: false
#| warning: false
#| error: false
#| title: Thermocouple Height Profile
TC_rawplotly
```
